"""The code was generated by Microsoft® Copilot AI Assistant (OpenAI)
"""
from PyQt5.QtWidgets import QCompleter, QLineEdit
from PyQt5.QtCore import QStringListModel, Qt

class DictCompleter(QCompleter):
    def __init__(self, parent=None):
        super(DictCompleter, self).__init__(parent)
        self.dict_data = {}
        self.model = QStringListModel(self)
        self.setModel(self.model)

    def update(self, dict_data):
        self.dict_data = dict_data
        # Convert dictionary keys to a list and set it as the model
        self.model.setStringList(list(self.dict_data.keys()))

    def add(self, key, value):
        self.dict_data[key] = value
        self.update(self.dict_data)

    def remove(self, key):
        if key in self.dict_data:
            del self.dict_data[key]
            self.update(self.dict_data)

class MyLineEdit(QLineEdit):
    def __init__(self, parent=None):
        super(MyLineEdit, self).__init__(parent)
        self.completer = DictCompleter()
        self.setCompleter(self.completer)

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Delete:
            text = self.text()
            self.completer.remove(text)
        super(MyLineEdit, self).keyPressEvent(event)