"""
Configuration and constants for Z-Scan application.

This module centralizes all configuration parameters, constants, and
hardware settings used throughout the application.
"""

__all__ = [
    "SILICA_BETA",
    "N_COMPONENTS",
    "INTEGRATION_STEPS",
    "CUVETTE_PATH_LENGTH",
    "MAX_DPHI0",
    "SOLVENT_T_SLIDER_MAX",
    "DAQ_TIMING_WAIT",
    "MOTOR_INIT_WAIT",
    "MOTOR_HOMING_WAIT",
    "MOTOR_POSITION_MAX",
    "COMPLETION_SOUND_FREQUENCY",
    "COMPLETION_SOUND_DURATION",
    "COMPLETION_SOUND_REPEATS",
    "COMPLETION_SOUND_INTERVAL",
]

from lib.constants import (
    SILICA_BETA,
    N_COMPONENTS,
    INTEGRATION_STEPS,
    CUVETTE_PATH_LENGTH,
    MAX_DPHI0,
    SOLVENT_T_SLIDER_MAX,
    SOLVENT_CA_SLIDER_CENTER_OFFSET,
    SOLVENT_OA_SLIDER_CENTER_OFFSET,
    SOLVENT_OA_SLIDER_MIN,
    SOLVENT_OA_SLIDER_MAX,
    SAMPLE_OA_SLIDER_CENTER_OFFSET,
    DPHI0_SCALE_FACTOR,
    BEAMWAIST_UM_SCALE,
    RAYLEIGH_LENGTH_MM_SCALE,
    LASER_INTENSITY_GW_SCALE,
    DAQ_TIMING_WAIT,
    MOTOR_INIT_WAIT,
    MOTOR_HOMING_WAIT,
    TIMER_UPDATE_INTERVAL,
    COMPLETION_SOUND_FREQUENCY,
    COMPLETION_SOUND_DURATION,
    COMPLETION_SOUND_REPEATS,
    COMPLETION_SOUND_INTERVAL,
    MOTOR_POSITION_MAX,
    RMS_NOISE_EDGE_WINDOW,
    DATA_NORMALIZATION_WINDOW,
    PLOT_PADDING_VERTICAL,
    PLOT_FONT_SIZE,
    DEFAULT_BEAMWAIST,
    DEFAULT_ZERO_LEVEL,
    DEFAULT_CENTER_POINT,
    OA_FITTING_PARAMS
)


